// <auto-generated />
using System;
using GamingZoneApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamingZoneApp.Data.Migrations
{
    [DbContext(typeof(GamingZoneDbContext))]
    [Migration("20260123160105_SeedGamesDevelopersAndPublishers")]
    partial class SeedGamesDevelopersAndPublishers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GamingZoneApp.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GamingZoneApp.Data.Models.ApplicationUserGame", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign Key referencing the Id of the user.");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign Key referencing the Id of the game.");

                    b.HasKey("UserId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("ApplicationUsersGames", t =>
                        {
                            t.HasComment("Mapping table for users' games");
                        });
                });

            modelBuilder.Entity("GamingZoneApp.Data.Models.Developer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identifier for the developer.");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("Brief information about the developer.");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("URL of the developer logo image.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("Name of the developer.");

                    b.HasKey("Id");

                    b.ToTable("Developers", t =>
                        {
                            t.HasComment("Developers in the system.");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("f75ee60f-4615-4bca-8a21-be507c6d3a49"),
                            Description = "Polish video game developer known for creating atmospheric psychological horror experiences with cutting-edge graphics and immersive storytelling.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Bloober+Team",
                            Name = "Bloober Team"
                        },
                        new
                        {
                            Id = new Guid("ba8230ef-c6b3-4be8-9408-43d57b2049c3"),
                            Description = "Polish video game studio renowned for creating story-driven, visually stunning games with deep narratives and meaningful player choice.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=CD+Projekt+Red",
                            Name = "CD Projekt Red"
                        },
                        new
                        {
                            Id = new Guid("d7197d8b-d7f4-49ba-b24c-87b2152c6440"),
                            Description = "Renowned Japanese video game developer celebrated for crafting challenging and immersive gameplay experiences with intricate level design and compelling boss battles.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=FromSoftware",
                            Name = "FromSoftware"
                        },
                        new
                        {
                            Id = new Guid("0b4120ce-a6f9-4b1d-b8d8-de31e4173f7e"),
                            Description = "Japanese video game developer and publisher known for creating legendary franchises and survival horror masterpieces with intense action gameplay.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Capcom",
                            Name = "Capcom"
                        },
                        new
                        {
                            Id = new Guid("4af65147-9ea5-4e30-a16d-de4750debe73"),
                            Description = "American video game developer owned by Sony Interactive Entertainment, famous for creating epic narrative-driven action games with stunning visuals.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Santa+Monica+Studio",
                            Name = "Santa Monica Studio"
                        },
                        new
                        {
                            Id = new Guid("c0d88616-83ce-416a-a034-11264b776cc1"),
                            Description = "Independent Australian video game developer known for creating meticulously crafted indie games with exceptional art direction and challenging gameplay.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Team+Cherry",
                            Name = "Team Cherry"
                        },
                        new
                        {
                            Id = new Guid("7596ad8e-5eaa-44da-a716-6ab508873b52"),
                            Description = "Independent video game studio renowned for creating visually stunning games with exceptional soundtracks and innovative gameplay mechanics.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Supergiant+Games",
                            Name = "Supergiant Games"
                        },
                        new
                        {
                            Id = new Guid("c81c009f-66c6-4c32-9c14-f3c9b68e20a3"),
                            Description = "Japanese video game developer and publisher known for creating epic JRPGs and iconic franchises with memorable characters and engaging storylines.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Square+Enix",
                            Name = "Square Enix"
                        },
                        new
                        {
                            Id = new Guid("0dd6b5e3-9d72-4a1a-89b0-a8651c6bebf4"),
                            Description = "American video game developer owned by Microsoft, famous for creating massive open-world RPGs with deep worlds and endless exploration opportunities.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Bethesda",
                            Name = "Bethesda Game Studios"
                        },
                        new
                        {
                            Id = new Guid("07dbe539-557e-4692-85e6-c875b1262a71"),
                            Description = "American video game developer and digital distribution company known for creating innovative, genre-defining games with exceptional design and storytelling.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Valve",
                            Name = "Valve"
                        },
                        new
                        {
                            Id = new Guid("ae06f7d4-7f50-411d-86af-c97ac324972e"),
                            Description = "American video game developer known for creating open-world action games with compelling narratives, stunning visual artistry, and engaging gameplay mechanics.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Sucker+Punch",
                            Name = "Sucker Punch Productions"
                        },
                        new
                        {
                            Id = new Guid("52753bfd-d052-4ac1-a648-c9ae2fda3ae4"),
                            Description = "Belgian video game developer known for creating deep, story-rich RPGs with complex mechanics, multiple endings, and exceptional player agency.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Larian+Studios",
                            Name = "Larian Studios"
                        },
                        new
                        {
                            Id = new Guid("7010a2f8-1545-48d8-bb52-86ea0995c45e"),
                            Description = "French video game developer founded by veteran developers, known for creating innovative action RPGs with unique artistic vision and creative gameplay.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Sandfall+Interactive",
                            Name = "Sandfall Interactive"
                        },
                        new
                        {
                            Id = new Guid("166ff532-b1c1-40ad-b6ef-85a73d049d1e"),
                            Description = "American video game developer known for creating fast-paced action games with intense gameplay and faithful adaptations of popular franchises.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Saber+Interactive",
                            Name = "Saber Interactive"
                        });
                });

            modelBuilder.Entity("GamingZoneApp.Data.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identifier of the videogame.");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("Description/trivia of the game.");

                    b.Property<Guid>("DeveloperId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign Key referencing the developer of the game.");

                    b.Property<int>("Genre")
                        .HasColumnType("int")
                        .HasComment("Genre of the videogame.");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("URL of the videogame image.");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Shows if the videogame is deleted.");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign Key referencing the publisher of the game.");

                    b.Property<decimal>("Rating")
                        .HasColumnType("DECIMAL(3,1)")
                        .HasComment("Videogame's average rating. Default value used, because users will rate the game");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2")
                        .HasComment("Videogame Release Date.");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(184)
                        .HasColumnType("nvarchar(184)")
                        .HasComment("Title of the videogame.");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Games", t =>
                        {
                            t.HasComment("Games in the system.");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("adaaad5d-49ee-4f9d-9de8-3d21f5333e6b"),
                            Description = "A faithful remake of the classic psychological horror masterpiece. Players navigate the fog-shrouded town of Silent Hill as James Sunderland, uncovering dark secrets and confronting manifestations of guilt and despair.",
                            DeveloperId = new Guid("f75ee60f-4615-4bca-8a21-be507c6d3a49"),
                            Genre = 9,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Silent+Hill+2",
                            IsDeleted = false,
                            PublisherId = new Guid("a0529584-8eb3-4880-8674-c4e5cc67b487"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2024, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Silent Hill 2 Remake"
                        },
                        new
                        {
                            Id = new Guid("55562e8e-cdda-4bbb-8603-e9c619b46580"),
                            Description = "An open-world fantasy RPG where you play as Geralt of Rivia, a monster hunter. Complete quests, explore vast landscapes, and make choices that shape the world around you. The game features one of gaming's most compelling stories.",
                            DeveloperId = new Guid("ba8230ef-c6b3-4be8-9408-43d57b2049c3"),
                            Genre = 8,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Witcher+3",
                            IsDeleted = false,
                            PublisherId = new Guid("f128d30f-d5df-4ea2-9638-6a3f2aef82dd"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2015, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Witcher 3: Wild Hunt"
                        },
                        new
                        {
                            Id = new Guid("4ad3f8ca-874e-41b3-ba2d-bfe4eaa2b334"),
                            Description = "An ambitious dystopian RPG set in the megacity of Night City. Play as V, a customizable mercenary navigating a world filled with corporate intrigue, high-tech augmentations, and morally complex choices.",
                            DeveloperId = new Guid("ba8230ef-c6b3-4be8-9408-43d57b2049c3"),
                            Genre = 8,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Cyberpunk+2077",
                            IsDeleted = false,
                            PublisherId = new Guid("f128d30f-d5df-4ea2-9638-6a3f2aef82dd"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2020, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cyberpunk 2077"
                        },
                        new
                        {
                            Id = new Guid("baaa2834-e824-4afb-8fd7-5911ad70390f"),
                            Description = "An open-world masterpiece combining challenging combat with expansive exploration. Traverse the Lands Between to restore the Elden Ring, facing formidable bosses and discovering hidden dungeons.",
                            DeveloperId = new Guid("d7197d8b-d7f4-49ba-b24c-87b2152c6440"),
                            Genre = 4,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Elden+Ring",
                            IsDeleted = false,
                            PublisherId = new Guid("8baa78a8-4139-409e-b8ab-78aac5b5fc48"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2022, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Elden Ring"
                        },
                        new
                        {
                            Id = new Guid("4e7d3a02-5a8b-487c-ae11-8a408e6a87c1"),
                            Description = "A challenging action-adventure game set in Sengoku-era Japan. Play as a shinobi warrior seeking revenge, utilizing parkour, sword combat, and skill-based gameplay. Defeat legendary bosses in this FromSoftware title.",
                            DeveloperId = new Guid("d7197d8b-d7f4-49ba-b24c-87b2152c6440"),
                            Genre = 4,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Sekiro",
                            IsDeleted = false,
                            PublisherId = new Guid("8baa78a8-4139-409e-b8ab-78aac5b5fc48"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2019, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sekiro: Shadows Die Twice"
                        },
                        new
                        {
                            Id = new Guid("b85a91b1-3d37-46fc-ba9a-db2593cd2616"),
                            Description = "The conclusion to the Dark Souls trilogy, featuring challenging combat, intricate level design, and dark fantasy storytelling. Explore interconnected worlds and defeat powerful enemies.",
                            DeveloperId = new Guid("d7197d8b-d7f4-49ba-b24c-87b2152c6440"),
                            Genre = 4,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Dark+Souls+III",
                            IsDeleted = false,
                            PublisherId = new Guid("8baa78a8-4139-409e-b8ab-78aac5b5fc48"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2016, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Dark Souls III"
                        },
                        new
                        {
                            Id = new Guid("bbbc7561-9fac-4795-9606-3f94c28ea92f"),
                            Description = "A survival horror game where you play as Ethan Winters searching for his daughter in a mysterious village. Encounter terrifying creatures, solve puzzles, and experience intense action.",
                            DeveloperId = new Guid("0b4120ce-a6f9-4b1d-b8d8-de31e4173f7e"),
                            Genre = 9,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Resident+Evil",
                            IsDeleted = false,
                            PublisherId = new Guid("e23228f4-77a4-448c-b816-ccb1826eed36"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2021, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Resident Evil Village"
                        },
                        new
                        {
                            Id = new Guid("ed8b79ef-f6a2-40bd-87a4-1ff887f72b4d"),
                            Description = "The epic conclusion to the Norse saga. Kratos and Atreus face the apocalypse as they prepare for the final battle. Experience stunning visuals, intense combat, and an emotional narrative.",
                            DeveloperId = new Guid("4af65147-9ea5-4e30-a16d-de4750debe73"),
                            Genre = 0,
                            ImageUrl = "https://via.placeholder.com/300x400?text=God+of+War",
                            IsDeleted = false,
                            PublisherId = new Guid("3c77575e-bad2-4408-901b-9ec193a7cfba"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2022, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "God of War Ragnarök"
                        },
                        new
                        {
                            Id = new Guid("96c36ea6-284b-464b-8ece-fae17e8b8cb7"),
                            Description = "A challenging 2D metroidvania game set in a haunted kingdom of insects. Explore interconnected caverns, defeat powerful bosses, and uncover the dark secrets of Hallownest.",
                            DeveloperId = new Guid("c0d88616-83ce-416a-a034-11264b776cc1"),
                            Genre = 21,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Hollow+Knight",
                            IsDeleted = false,
                            PublisherId = new Guid("b037a40e-b701-4bdc-a5c0-96b0fdd92619"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2017, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Hollow Knight"
                        },
                        new
                        {
                            Id = new Guid("66bc4087-06f8-418e-9c4a-8908bc6b7771"),
                            Description = "A roguelike action game where you escape from Hades, the Greek underworld. Repeatedly attempt runs through procedurally generated dungeons, upgrading your abilities and uncovering rich mythology.",
                            DeveloperId = new Guid("7596ad8e-5eaa-44da-a716-6ab508873b52"),
                            Genre = 15,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Hades",
                            IsDeleted = false,
                            PublisherId = new Guid("0039fd7b-fdc2-4218-b942-e24ec3f3cf1f"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2020, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Hades"
                        },
                        new
                        {
                            Id = new Guid("ecbda2ec-594d-419d-8b55-9ecb4358ef41"),
                            Description = "A modern reimagining of the classic JRPG. Play as Cloud and his allies in the sprawling metropolis of Midgar. Experience real-time combat and an expanded story.",
                            DeveloperId = new Guid("c81c009f-66c6-4c32-9c14-f3c9b68e20a3"),
                            Genre = 16,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Final+Fantasy+VII",
                            IsDeleted = false,
                            PublisherId = new Guid("1a94a706-493a-4ec2-b3e1-3cd802128f59"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2020, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Final Fantasy VII Remake"
                        },
                        new
                        {
                            Id = new Guid("ab827d8a-311d-46cd-ad74-3742e07bfc5e"),
                            Description = "Bethesda's ambitious space RPG featuring procedurally generated planets and a massive universe to explore. Create your character, build your spaceship, and embark on quests across hundreds of worlds.",
                            DeveloperId = new Guid("0dd6b5e3-9d72-4a1a-89b0-a8651c6bebf4"),
                            Genre = 2,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Starfield",
                            IsDeleted = false,
                            PublisherId = new Guid("bad774ec-fc82-479d-800c-97c5bd602884"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2023, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Starfield"
                        },
                        new
                        {
                            Id = new Guid("ed221215-c642-4077-b111-b770619b49c2"),
                            Description = "A puzzle-platformer featuring innovative portal mechanics. Use your portal gun to manipulate space, solve complex puzzles, and navigate through hilarious tests.",
                            DeveloperId = new Guid("07dbe539-557e-4692-85e6-c875b1262a71"),
                            Genre = 11,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Portal+2",
                            IsDeleted = false,
                            PublisherId = new Guid("e89f7368-94f7-4f55-8e0d-a03333659abb"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2011, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Portal 2"
                        },
                        new
                        {
                            Id = new Guid("31af3372-60e4-4fa2-a2a6-35032f396601"),
                            Description = "An open-world action-adventure set in 13th-century Japan. Play as Jin Sakai, a samurai warrior defending his homeland from invading Mongol forces. Experience stunning visuals, intense sword combat, and a compelling tale of honor and sacrifice.",
                            DeveloperId = new Guid("ae06f7d4-7f50-411d-86af-c97ac324972e"),
                            Genre = 0,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Ghost+of+Tsushima",
                            IsDeleted = false,
                            PublisherId = new Guid("3c77575e-bad2-4408-901b-9ec193a7cfba"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2020, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ghost of Tsushima"
                        },
                        new
                        {
                            Id = new Guid("faaa0756-7312-400c-9ba5-a581e4c90faf"),
                            Description = "Hunt massive monsters in a sprawling open world. Master various weapons, craft armor, and work with other hunters to take down legendary creatures.",
                            DeveloperId = new Guid("0b4120ce-a6f9-4b1d-b8d8-de31e4173f7e"),
                            Genre = 8,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Monster+Hunter",
                            IsDeleted = false,
                            PublisherId = new Guid("e23228f4-77a4-448c-b816-ccb1826eed36"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2018, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Monster Hunter: World"
                        },
                        new
                        {
                            Id = new Guid("bb09f7dd-442f-4e5e-b12c-e13a68fffa2f"),
                            Description = "A massive CRPG set in the Dungeons & Dragons universe. Create your character, make impactful choices, and enjoy an incredibly deep story with multiple endings.",
                            DeveloperId = new Guid("52753bfd-d052-4ac1-a648-c9ae2fda3ae4"),
                            Genre = 20,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Baldurs+Gate+3",
                            IsDeleted = false,
                            PublisherId = new Guid("e2b91da3-3f00-4eb4-9785-643acbcf4c55"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2023, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Baldur's Gate 3"
                        },
                        new
                        {
                            Id = new Guid("2ab1107e-a9a0-4bfc-b366-034ebb4a73a1"),
                            Description = "The latest entry in the legendary fighting game franchise. Master diverse characters, execute precise combos, and compete online or offline.",
                            DeveloperId = new Guid("0b4120ce-a6f9-4b1d-b8d8-de31e4173f7e"),
                            Genre = 5,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Street+Fighter+6",
                            IsDeleted = false,
                            PublisherId = new Guid("e23228f4-77a4-448c-b816-ccb1826eed36"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2023, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Street Fighter 6"
                        },
                        new
                        {
                            Id = new Guid("38c117e0-2416-4d69-a39a-2b4141c218b2"),
                            Description = "A vibrant action RPG set in a beautiful watercolor-inspired world. Embark on an expedition to defeat cosmic corruption and discover the secrets of the land. Features real-time tactical combat and rich exploration.",
                            DeveloperId = new Guid("7010a2f8-1545-48d8-bb52-86ea0995c45e"),
                            Genre = 8,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Clair+Obscur",
                            IsDeleted = false,
                            PublisherId = new Guid("556474fc-388b-48a7-9bd2-c45528b09bb1"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Clair Obscur: Expedition 33"
                        },
                        new
                        {
                            Id = new Guid("24c4a7ef-7552-4931-ba8b-c5dbe536b323"),
                            Description = "An intense third-person shooter set in the grim Warhammer 40K universe. Play as a Space Marine and battle hordes of enemies using devastating weapons and melee combat. Experience fast-paced action and epic battles.",
                            DeveloperId = new Guid("166ff532-b1c1-40ad-b6ef-85a73d049d1e"),
                            Genre = 7,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Space+Marine+2",
                            IsDeleted = false,
                            PublisherId = new Guid("ed820b54-96c2-4fbf-a533-09b193c08028"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2024, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Warhammer 40,000: Space Marine 2"
                        });
                });

            modelBuilder.Entity("GamingZoneApp.Data.Models.Publisher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identifier for the publisher.");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("Brief information about the publisher.");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("URL of the publisher logo image.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("Name of the publisher.");

                    b.HasKey("Id");

                    b.ToTable("Publishers", t =>
                        {
                            t.HasComment("Publishers in the system.");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0529584-8eb3-4880-8674-c4e5cc67b487"),
                            Description = "Japanese video game publisher recognized for creating atmospheric and psychologically intense horror games that push the boundaries of interactive storytelling.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Konami",
                            Name = "Konami"
                        },
                        new
                        {
                            Id = new Guid("f128d30f-d5df-4ea2-9638-6a3f2aef82dd"),
                            Description = "Polish video game publisher and distributor known for supporting independent studios and publishing award-winning narrative-driven games.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=CD+Projekt",
                            Name = "CD Projekt"
                        },
                        new
                        {
                            Id = new Guid("8baa78a8-4139-409e-b8ab-78aac5b5fc48"),
                            Description = "Japanese video game publisher specializing in action-packed games and collaborations with renowned developers to create premium gaming experiences.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Bandai+Namco",
                            Name = "Bandai Namco Entertainment"
                        },
                        new
                        {
                            Id = new Guid("e23228f4-77a4-448c-b816-ccb1826eed36"),
                            Description = "Japanese video game publisher known for creating legendary survival horror franchises and action games with exceptional design and storytelling.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Capcom",
                            Name = "Capcom"
                        },
                        new
                        {
                            Id = new Guid("3c77575e-bad2-4408-901b-9ec193a7cfba"),
                            Description = "American video game publisher and division of Sony, famous for publishing exclusive PlayStation titles and supporting innovative game development.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Sony+Interactive",
                            Name = "Sony Interactive Entertainment"
                        },
                        new
                        {
                            Id = new Guid("b037a40e-b701-4bdc-a5c0-96b0fdd92619"),
                            Description = "Independent publisher known for releasing meticulously crafted indie games with exceptional artistic vision and challenging gameplay.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Team+Cherry",
                            Name = "Team Cherry"
                        },
                        new
                        {
                            Id = new Guid("0039fd7b-fdc2-4218-b942-e24ec3f3cf1f"),
                            Description = "Independent video game publisher renowned for creating visually stunning games with exceptional soundtracks and innovative gameplay mechanics.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Supergiant+Games",
                            Name = "Supergiant Games"
                        },
                        new
                        {
                            Id = new Guid("1a94a706-493a-4ec2-b3e1-3cd802128f59"),
                            Description = "Japanese video game publisher known for publishing epic JRPGs and iconic franchises with memorable characters and engaging storytelling.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Square+Enix",
                            Name = "Square Enix"
                        },
                        new
                        {
                            Id = new Guid("bad774ec-fc82-479d-800c-97c5bd602884"),
                            Description = "American video game publisher owned by Microsoft, famous for publishing massive open-world RPGs and supporting innovative game development.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Bethesda",
                            Name = "Bethesda Softworks"
                        },
                        new
                        {
                            Id = new Guid("e89f7368-94f7-4f55-8e0d-a03333659abb"),
                            Description = "American video game publisher and digital distribution platform known for innovative, genre-defining games and digital distribution excellence.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Valve",
                            Name = "Valve"
                        },
                        new
                        {
                            Id = new Guid("e2b91da3-3f00-4eb4-9785-643acbcf4c55"),
                            Description = "Belgian video game publisher known for publishing deep, story-rich RPGs with complex mechanics, multiple endings, and exceptional player agency.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Larian+Studios",
                            Name = "Larian Studios"
                        },
                        new
                        {
                            Id = new Guid("556474fc-388b-48a7-9bd2-c45528b09bb1"),
                            Description = "Independent video game publisher known for supporting innovative action RPGs and artistic games from talented developers with unique creative vision.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Kepler+Interactive",
                            Name = "Kepler Interactive"
                        },
                        new
                        {
                            Id = new Guid("ed820b54-96c2-4fbf-a533-09b193c08028"),
                            Description = "European video game publisher known for publishing action-packed games and supporting diverse game genres from independent to AAA studios.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Focus+Entertainment",
                            Name = "Focus Entertainment"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GamingZoneApp.Data.Models.ApplicationUserGame", b =>
                {
                    b.HasOne("GamingZoneApp.Data.Models.Game", "Game")
                        .WithMany("GamesUsers")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamingZoneApp.Data.Models.ApplicationUser", "User")
                        .WithMany("UsersGames")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GamingZoneApp.Data.Models.Game", b =>
                {
                    b.HasOne("GamingZoneApp.Data.Models.Developer", "Developer")
                        .WithMany("GamesDeveloped")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamingZoneApp.Data.Models.Publisher", "Publisher")
                        .WithMany("GamesPublished")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("GamingZoneApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("GamingZoneApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamingZoneApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("GamingZoneApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamingZoneApp.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("UsersGames");
                });

            modelBuilder.Entity("GamingZoneApp.Data.Models.Developer", b =>
                {
                    b.Navigation("GamesDeveloped");
                });

            modelBuilder.Entity("GamingZoneApp.Data.Models.Game", b =>
                {
                    b.Navigation("GamesUsers");
                });

            modelBuilder.Entity("GamingZoneApp.Data.Models.Publisher", b =>
                {
                    b.Navigation("GamesPublished");
                });
#pragma warning restore 612, 618
        }
    }
}
