// <auto-generated />
using System;
using GamingZoneApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamingZoneApp.Data.Migrations
{
    [DbContext(typeof(GamingZoneDbContext))]
    [Migration("20260216110252_RemovedDevelopersAndPublishersEntriesFromTheDatabase")]
    partial class RemovedDevelopersAndPublishersEntriesFromTheDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GamingZoneApp.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e303f8ff-8c3d-4ec7-bdc9-bc5efa05325f"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4a0c1b05-ac2f-43ba-8eee-a12e7df38f24",
                            Email = "admin@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEJXstDNYyN5/xyLjHu/NlqJtTjboQSZXhYrePMblQE2VM1Teys77eZHm0zSSCKF7mg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d1170ce6-a483-4bac-bbd8-5260b044b906",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("GamingZoneApp.Data.Models.ApplicationUserGame", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign Key referencing the Id of the user.");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign Key referencing the Id of the game.");

                    b.HasKey("UserId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("ApplicationUsersGames", t =>
                        {
                            t.HasComment("Mapping table for users' games");
                        });
                });

            modelBuilder.Entity("GamingZoneApp.Data.Models.Developer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identifier for the developer.");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("Brief information about the developer.");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("URL of the developer logo image.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("Name of the developer.");

                    b.HasKey("Id");

                    b.ToTable("Developers", t =>
                        {
                            t.HasComment("Developers in the system.");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("f75ee60f-4615-4bca-8a21-be507c6d3a49"),
                            Description = "European video game developer known for creating atmospheric psychological horror experiences with cutting-edge graphics and immersive storytelling.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Nightshade+Studios",
                            Name = "Nightshade Studios"
                        },
                        new
                        {
                            Id = new Guid("d7197d8b-d7f4-49ba-b24c-87b2152c6440"),
                            Description = "Renowned video game developer celebrated for crafting challenging and immersive gameplay experiences with intricate level design and compelling boss battles.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Iron+Tempest",
                            Name = "Iron Tempest Games"
                        },
                        new
                        {
                            Id = new Guid("0b4120ce-a6f9-4b1d-b8d8-de31e4173f7e"),
                            Description = "Veteran video game developer and publisher known for creating legendary franchises and survival horror masterpieces with intense action gameplay.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Phoenix+Rising",
                            Name = "Phoenix Rising Interactive"
                        },
                        new
                        {
                            Id = new Guid("c0d88616-83ce-416a-a034-11264b776cc1"),
                            Description = "Independent video game developer known for creating meticulously crafted indie games with exceptional art direction and challenging gameplay.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Pixel+Hollow",
                            Name = "Pixel Hollow Studios"
                        },
                        new
                        {
                            Id = new Guid("7010a2f8-1545-48d8-bb52-86ea0995c45e"),
                            Description = "Boutique video game developer founded by industry veterans, known for creating innovative action RPGs with unique artistic vision and creative gameplay.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Prism+Voyage",
                            Name = "Prism Voyage Studios"
                        },
                        new
                        {
                            Id = new Guid("166ff532-b1c1-40ad-b6ef-85a73d049d1e"),
                            Description = "Dynamic video game developer known for creating fast-paced action games with intense gameplay and large-scale multiplayer experiences.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Titan+Forge",
                            Name = "Titan Forge Games"
                        });
                });

            modelBuilder.Entity("GamingZoneApp.Data.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identifier of the videogame.");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("Description/trivia of the game.");

                    b.Property<Guid>("DeveloperId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign Key referencing the developer of the game.");

                    b.Property<int>("Genre")
                        .HasColumnType("int")
                        .HasComment("Genre of the videogame.");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("URL of the videogame image.");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Shows if the videogame is deleted.");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign Key referencing the publisher of the game.");

                    b.Property<decimal>("Rating")
                        .HasColumnType("DECIMAL(3,1)")
                        .HasComment("Videogame's average rating. Default value used, because users will rate the game");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2")
                        .HasComment("Videogame Release Date.");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(184)
                        .HasColumnType("nvarchar(184)")
                        .HasComment("Title of the videogame.");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign Key referencing the user who added the game.");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("PublisherId");

                    b.HasIndex("UserId");

                    b.ToTable("Games", t =>
                        {
                            t.HasComment("Games in the system.");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("adaaad5d-49ee-4f9d-9de8-3d21f5333e6b"),
                            Description = "Venture into the abandoned Bloodlight Sanatorium where shadows breathe and walls remember. As paranormal investigator Elena Voss, unravel decades of buried secrets while evading entities that feed on fear itself.",
                            DeveloperId = new Guid("f75ee60f-4615-4bca-8a21-be507c6d3a49"),
                            Genre = 9,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Whispers+of+Hollowmere",
                            IsDeleted = false,
                            PublisherId = new Guid("a0529584-8eb3-4880-8674-c4e5cc67b487"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2024, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Bloodlight Sanatorium",
                            UserId = new Guid("e303f8ff-8c3d-4ec7-bdc9-bc5efa05325f")
                        },
                        new
                        {
                            Id = new Guid("4e7d3a02-5a8b-487c-ae11-8a408e6a87c1"),
                            Description = "Disgraced and left for dead, rise as a nameless swordsman in the war-ravaged Kiyohara Province. Master the forbidden Crimson Style, hunt those who betrayed you, and carve a path through oni and warlord alike.",
                            DeveloperId = new Guid("d7197d8b-d7f4-49ba-b24c-87b2152c6440"),
                            Genre = 4,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Oath+of+Vermillion+Ronin",
                            IsDeleted = false,
                            PublisherId = new Guid("8baa78a8-4139-409e-b8ab-78aac5b5fc48"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2019, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Oath of the Vermillion Ronin",
                            UserId = new Guid("e303f8ff-8c3d-4ec7-bdc9-bc5efa05325f")
                        },
                        new
                        {
                            Id = new Guid("bbbc7561-9fac-4795-9606-3f94c28ea92f"),
                            Description = "Something ancient stirs beneath Ravencrest Estate. As Dominic Ashford, search for your missing daughter through decaying halls, confront manifestations of familial guilt, and survive a night where the house itself hunts you.",
                            DeveloperId = new Guid("0b4120ce-a6f9-4b1d-b8d8-de31e4173f7e"),
                            Genre = 9,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Ravencrest+Estate",
                            IsDeleted = false,
                            PublisherId = new Guid("e23228f4-77a4-448c-b816-ccb1826eed36"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2021, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Mystery of Ravencrest",
                            UserId = new Guid("e303f8ff-8c3d-4ec7-bdc9-bc5efa05325f")
                        },
                        new
                        {
                            Id = new Guid("96c36ea6-284b-464b-8ece-fae17e8b8cb7"),
                            Description = "Deep within the Brass Hollows, a clockwork civilization crumbles. Guide the last Tinker through labyrinthine foundries, rewire ancient mechanisms, and discover why the Great Engine fell silent centuries ago.",
                            DeveloperId = new Guid("c0d88616-83ce-416a-a034-11264b776cc1"),
                            Genre = 21,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Gearwright+Caverns",
                            IsDeleted = false,
                            PublisherId = new Guid("b037a40e-b701-4bdc-a5c0-96b0fdd92619"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2017, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gearwright Caverns",
                            UserId = new Guid("e303f8ff-8c3d-4ec7-bdc9-bc5efa05325f")
                        },
                        new
                        {
                            Id = new Guid("38c117e0-2416-4d69-a39a-2b4141c218b2"),
                            Description = "Sail between floating archipelagos in a world torn asunder by magical cataclysm. Recruit a crew of outcasts, uncover the secrets of the Sundering, and restore balance before the remaining islands fall into the void.",
                            DeveloperId = new Guid("7010a2f8-1545-48d8-bb52-86ea0995c45e"),
                            Genre = 8,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Wanderers+Shattered+Isles",
                            IsDeleted = false,
                            PublisherId = new Guid("556474fc-388b-48a7-9bd2-c45528b09bb1"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Wanderers of the Shattered Isles",
                            UserId = new Guid("e303f8ff-8c3d-4ec7-bdc9-bc5efa05325f")
                        },
                        new
                        {
                            Id = new Guid("24c4a7ef-7552-4931-ba8b-c5dbe536b323"),
                            Description = "The Hegemony's elite answer humanity's darkest hour. Lead Sergeant Kira Vance through xeno-infested worlds, command squad tactics in brutal firefights, and uncover a conspiracy that threatens the entire frontier.",
                            DeveloperId = new Guid("166ff532-b1c1-40ad-b6ef-85a73d049d1e"),
                            Genre = 7,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Stellarborne+Legionnaires+II",
                            IsDeleted = false,
                            PublisherId = new Guid("ed820b54-96c2-4fbf-a533-09b193c08028"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2024, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Galactic Crusaders II",
                            UserId = new Guid("e303f8ff-8c3d-4ec7-bdc9-bc5efa05325f")
                        });
                });

            modelBuilder.Entity("GamingZoneApp.Data.Models.Publisher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identifier for the publisher.");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("Brief information about the publisher.");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("URL of the publisher logo image.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("Name of the publisher.");

                    b.HasKey("Id");

                    b.ToTable("Publishers", t =>
                        {
                            t.HasComment("Publishers in the system.");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0529584-8eb3-4880-8674-c4e5cc67b487"),
                            Description = "International video game publisher recognized for creating atmospheric and psychologically intense horror games that push the boundaries of interactive storytelling.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Phantom+Gate",
                            Name = "Phantom Gate Publishing"
                        },
                        new
                        {
                            Id = new Guid("8baa78a8-4139-409e-b8ab-78aac5b5fc48"),
                            Description = "Major video game publisher specializing in action-packed games and collaborations with renowned developers to create premium gaming experiences.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Dragon+Crown",
                            Name = "Dragon Crown Entertainment"
                        },
                        new
                        {
                            Id = new Guid("e23228f4-77a4-448c-b816-ccb1826eed36"),
                            Description = "Established video game publisher known for creating legendary survival horror franchises and action games with exceptional design and storytelling.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Phoenix+Rising+Pub",
                            Name = "Phoenix Rising Publishing"
                        },
                        new
                        {
                            Id = new Guid("b037a40e-b701-4bdc-a5c0-96b0fdd92619"),
                            Description = "Independent publisher known for releasing meticulously crafted indie games with exceptional artistic vision and challenging gameplay.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Pixel+Hollow+Pub",
                            Name = "Pixel Hollow Publishing"
                        },
                        new
                        {
                            Id = new Guid("556474fc-388b-48a7-9bd2-c45528b09bb1"),
                            Description = "Independent video game publisher known for supporting innovative action RPGs and artistic games from talented developers with unique creative vision.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Prism+Voyage+Pub",
                            Name = "Prism Voyage Publishing"
                        },
                        new
                        {
                            Id = new Guid("ed820b54-96c2-4fbf-a533-09b193c08028"),
                            Description = "International video game publisher known for publishing action-packed games and supporting diverse game genres from independent to AAA studios.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Titan+Forge+Pub",
                            Name = "Titan Forge Publishing"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GamingZoneApp.Data.Models.ApplicationUserGame", b =>
                {
                    b.HasOne("GamingZoneApp.Data.Models.Game", "Game")
                        .WithMany("GamesUsers")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamingZoneApp.Data.Models.ApplicationUser", "User")
                        .WithMany("UsersGames")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GamingZoneApp.Data.Models.Game", b =>
                {
                    b.HasOne("GamingZoneApp.Data.Models.Developer", "Developer")
                        .WithMany("GamesDeveloped")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamingZoneApp.Data.Models.Publisher", "Publisher")
                        .WithMany("GamesPublished")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamingZoneApp.Data.Models.ApplicationUser", "User")
                        .WithMany("MyGames")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");

                    b.Navigation("Publisher");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("GamingZoneApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("GamingZoneApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamingZoneApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("GamingZoneApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamingZoneApp.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("MyGames");

                    b.Navigation("UsersGames");
                });

            modelBuilder.Entity("GamingZoneApp.Data.Models.Developer", b =>
                {
                    b.Navigation("GamesDeveloped");
                });

            modelBuilder.Entity("GamingZoneApp.Data.Models.Game", b =>
                {
                    b.Navigation("GamesUsers");
                });

            modelBuilder.Entity("GamingZoneApp.Data.Models.Publisher", b =>
                {
                    b.Navigation("GamesPublished");
                });
#pragma warning restore 612, 618
        }
    }
}
