// <auto-generated />
using System;
using GamingZoneApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamingZoneApp.Data.Migrations
{
    [DbContext(typeof(GamingZoneDbContext))]
    [Migration("20260212153046_AddedOneToManyRelationForGameAndUser")]
    partial class AddedOneToManyRelationForGameAndUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GamingZoneApp.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GamingZoneApp.Data.Models.ApplicationUserGame", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign Key referencing the Id of the user.");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign Key referencing the Id of the game.");

                    b.HasKey("UserId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("ApplicationUsersGames", t =>
                        {
                            t.HasComment("Mapping table for users' games");
                        });
                });

            modelBuilder.Entity("GamingZoneApp.Data.Models.Developer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identifier for the developer.");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("Brief information about the developer.");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("URL of the developer logo image.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("Name of the developer.");

                    b.HasKey("Id");

                    b.ToTable("Developers", t =>
                        {
                            t.HasComment("Developers in the system.");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("f75ee60f-4615-4bca-8a21-be507c6d3a49"),
                            Description = "European video game developer known for creating atmospheric psychological horror experiences with cutting-edge graphics and immersive storytelling.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Nightshade+Studios",
                            Name = "Nightshade Studios"
                        },
                        new
                        {
                            Id = new Guid("ba8230ef-c6b3-4be8-9408-43d57b2049c3"),
                            Description = "Award-winning studio renowned for creating story-driven, visually stunning games with deep narratives and meaningful player choice.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Crimson+Forge",
                            Name = "Crimson Forge Entertainment"
                        },
                        new
                        {
                            Id = new Guid("d7197d8b-d7f4-49ba-b24c-87b2152c6440"),
                            Description = "Renowned video game developer celebrated for crafting challenging and immersive gameplay experiences with intricate level design and compelling boss battles.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Iron+Tempest",
                            Name = "Iron Tempest Games"
                        },
                        new
                        {
                            Id = new Guid("0b4120ce-a6f9-4b1d-b8d8-de31e4173f7e"),
                            Description = "Veteran video game developer and publisher known for creating legendary franchises and survival horror masterpieces with intense action gameplay.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Phoenix+Rising",
                            Name = "Phoenix Rising Interactive"
                        },
                        new
                        {
                            Id = new Guid("4af65147-9ea5-4e30-a16d-de4750debe73"),
                            Description = "Premier video game developer famous for creating epic narrative-driven action games with stunning visuals and cinematic presentation.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Olympus+Digital",
                            Name = "Olympus Digital"
                        },
                        new
                        {
                            Id = new Guid("c0d88616-83ce-416a-a034-11264b776cc1"),
                            Description = "Independent video game developer known for creating meticulously crafted indie games with exceptional art direction and challenging gameplay.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Pixel+Hollow",
                            Name = "Pixel Hollow Studios"
                        },
                        new
                        {
                            Id = new Guid("7596ad8e-5eaa-44da-a716-6ab508873b52"),
                            Description = "Independent video game studio renowned for creating visually stunning games with exceptional soundtracks and innovative gameplay mechanics.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Ember+Flame",
                            Name = "Ember Flame Games"
                        },
                        new
                        {
                            Id = new Guid("c81c009f-66c6-4c32-9c14-f3c9b68e20a3"),
                            Description = "Major video game developer and publisher known for creating epic JRPGs and iconic franchises with memorable characters and engaging storylines.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Crystal+Dawn",
                            Name = "Crystal Dawn Entertainment"
                        },
                        new
                        {
                            Id = new Guid("0dd6b5e3-9d72-4a1a-89b0-a8651c6bebf4"),
                            Description = "Leading video game developer famous for creating massive open-world RPGs with deep worlds and endless exploration opportunities.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Starbound+Studios",
                            Name = "Starbound Studios"
                        },
                        new
                        {
                            Id = new Guid("07dbe539-557e-4692-85e6-c875b1262a71"),
                            Description = "Innovative video game developer known for creating genre-defining games with exceptional design, storytelling, and groundbreaking mechanics.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Quantum+Rift",
                            Name = "Quantum Rift Software"
                        },
                        new
                        {
                            Id = new Guid("ae06f7d4-7f50-411d-86af-c97ac324972e"),
                            Description = "Acclaimed video game developer known for creating open-world action games with compelling narratives, stunning visual artistry, and engaging gameplay.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Shadow+Blade",
                            Name = "Shadow Blade Productions"
                        },
                        new
                        {
                            Id = new Guid("52753bfd-d052-4ac1-a648-c9ae2fda3ae4"),
                            Description = "European video game developer known for creating deep, story-rich RPGs with complex mechanics, multiple endings, and exceptional player agency.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Arcane+Depths",
                            Name = "Arcane Depths Interactive"
                        },
                        new
                        {
                            Id = new Guid("7010a2f8-1545-48d8-bb52-86ea0995c45e"),
                            Description = "Boutique video game developer founded by industry veterans, known for creating innovative action RPGs with unique artistic vision and creative gameplay.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Prism+Voyage",
                            Name = "Prism Voyage Studios"
                        },
                        new
                        {
                            Id = new Guid("166ff532-b1c1-40ad-b6ef-85a73d049d1e"),
                            Description = "Dynamic video game developer known for creating fast-paced action games with intense gameplay and large-scale multiplayer experiences.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Titan+Forge",
                            Name = "Titan Forge Games"
                        });
                });

            modelBuilder.Entity("GamingZoneApp.Data.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identifier of the videogame.");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("Description/trivia of the game.");

                    b.Property<Guid>("DeveloperId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign Key referencing the developer of the game.");

                    b.Property<int>("Genre")
                        .HasColumnType("int")
                        .HasComment("Genre of the videogame.");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("URL of the videogame image.");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Shows if the videogame is deleted.");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Foreign Key referencing the publisher of the game.");

                    b.Property<decimal>("Rating")
                        .HasColumnType("DECIMAL(3,1)")
                        .HasComment("Videogame's average rating. Default value used, because users will rate the game");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2")
                        .HasComment("Videogame Release Date.");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(184)
                        .HasColumnType("nvarchar(184)")
                        .HasComment("Title of the videogame.");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("PublisherId");

                    b.HasIndex("UserId");

                    b.ToTable("Games", t =>
                        {
                            t.HasComment("Games in the system.");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("adaaad5d-49ee-4f9d-9de8-3d21f5333e6b"),
                            Description = "Venture into the abandoned Bloodlight Sanatorium where shadows breathe and walls remember. As paranormal investigator Elena Voss, unravel decades of buried secrets while evading entities that feed on fear itself.",
                            DeveloperId = new Guid("f75ee60f-4615-4bca-8a21-be507c6d3a49"),
                            Genre = 9,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Whispers+of+Hollowmere",
                            IsDeleted = false,
                            PublisherId = new Guid("a0529584-8eb3-4880-8674-c4e5cc67b487"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2024, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Bloodlight Sanatorium"
                        },
                        new
                        {
                            Id = new Guid("55562e8e-cdda-4bbb-8603-e9c619b46580"),
                            Description = "Become Varen Duskwood, a wandering archivist thrust into a continental war over forbidden knowledge. Traverse five distinct kingdoms, forge pacts with ancient spirits, and decide which truths deserve to survive.",
                            DeveloperId = new Guid("ba8230ef-c6b3-4be8-9408-43d57b2049c3"),
                            Genre = 8,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Lorekeepers+of+Aethermoor",
                            IsDeleted = false,
                            PublisherId = new Guid("f128d30f-d5df-4ea2-9638-6a3f2aef82dd"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2015, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Lorekeepers of Aethermoor"
                        },
                        new
                        {
                            Id = new Guid("4ad3f8ca-874e-41b3-ba2d-bfe4eaa2b334"),
                            Description = "In the towering megastructure of Arcturus Prime, play as Cipher-7, a rogue synthetic seeking answers about their origins. Infiltrate corporate enclaves, hack neural networks, and question what it means to be alive.",
                            DeveloperId = new Guid("ba8230ef-c6b3-4be8-9408-43d57b2049c3"),
                            Genre = 8,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Synthetica+Fractured+Grid",
                            IsDeleted = false,
                            PublisherId = new Guid("f128d30f-d5df-4ea2-9638-6a3f2aef82dd"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2020, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Synthetica: Fractured Grid"
                        },
                        new
                        {
                            Id = new Guid("baaa2834-e824-4afb-8fd7-5911ad70390f"),
                            Description = "The Blighted Throne awaits a new sovereign. Cross treacherous mirelands, challenge colossal guardians born of dying gods, and piece together a shattered realm where every victory carves your legend into stone.",
                            DeveloperId = new Guid("d7197d8b-d7f4-49ba-b24c-87b2152c6440"),
                            Genre = 4,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Thornveil+Dominion",
                            IsDeleted = false,
                            PublisherId = new Guid("8baa78a8-4139-409e-b8ab-78aac5b5fc48"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2022, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Thornveil Dominion"
                        },
                        new
                        {
                            Id = new Guid("4e7d3a02-5a8b-487c-ae11-8a408e6a87c1"),
                            Description = "Disgraced and left for dead, rise as a nameless swordsman in the war-ravaged Kiyohara Province. Master the forbidden Crimson Style, hunt those who betrayed you, and carve a path through oni and warlord alike.",
                            DeveloperId = new Guid("d7197d8b-d7f4-49ba-b24c-87b2152c6440"),
                            Genre = 4,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Oath+of+Vermillion+Ronin",
                            IsDeleted = false,
                            PublisherId = new Guid("8baa78a8-4139-409e-b8ab-78aac5b5fc48"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2019, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Oath of the Vermillion Ronin"
                        },
                        new
                        {
                            Id = new Guid("b85a91b1-3d37-46fc-ba9a-db2593cd2616"),
                            Description = "Descend into the smoldering ruins of the Embervault, where the First Flame's remnants twist reality. Face relentless horrors, uncover the Pyrekeepers' tragic fate, and choose whether to rekindle hope or embrace oblivion.",
                            DeveloperId = new Guid("d7197d8b-d7f4-49ba-b24c-87b2152c6440"),
                            Genre = 4,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Embervault+Requiem",
                            IsDeleted = false,
                            PublisherId = new Guid("8baa78a8-4139-409e-b8ab-78aac5b5fc48"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2016, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Embervault Requiem"
                        },
                        new
                        {
                            Id = new Guid("bbbc7561-9fac-4795-9606-3f94c28ea92f"),
                            Description = "Something ancient stirs beneath Ravencrest Estate. As Dominic Ashford, search for your missing daughter through decaying halls, confront manifestations of familial guilt, and survive a night where the house itself hunts you.",
                            DeveloperId = new Guid("0b4120ce-a6f9-4b1d-b8d8-de31e4173f7e"),
                            Genre = 9,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Ravencrest+Estate",
                            IsDeleted = false,
                            PublisherId = new Guid("e23228f4-77a4-448c-b816-ccb1826eed36"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2021, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Mystery of Ravencrest"
                        },
                        new
                        {
                            Id = new Guid("ed8b79ef-f6a2-40bd-87a4-1ff887f72b4d"),
                            Description = "Ragnarok approaches as Halvard and his son Eirik defy fate itself. Wield thunder-forged weapons, traverse the Nine Branches, and challenge beings of primordial power in this climactic tale of sacrifice and legacy.",
                            DeveloperId = new Guid("4af65147-9ea5-4e30-a16d-de4750debe73"),
                            Genre = 0,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Fury+of+Stormborn",
                            IsDeleted = false,
                            PublisherId = new Guid("3c77575e-bad2-4408-901b-9ec193a7cfba"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2022, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fury of the Stormborn"
                        },
                        new
                        {
                            Id = new Guid("96c36ea6-284b-464b-8ece-fae17e8b8cb7"),
                            Description = "Deep within the Brass Hollows, a clockwork civilization crumbles. Guide the last Tinker through labyrinthine foundries, rewire ancient mechanisms, and discover why the Great Engine fell silent centuries ago.",
                            DeveloperId = new Guid("c0d88616-83ce-416a-a034-11264b776cc1"),
                            Genre = 21,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Gearwright+Caverns",
                            IsDeleted = false,
                            PublisherId = new Guid("b037a40e-b701-4bdc-a5c0-96b0fdd92619"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2017, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gearwright Caverns"
                        },
                        new
                        {
                            Id = new Guid("66bc4087-06f8-418e-9c4a-8908bc6b7771"),
                            Description = "Condemned to the Scorching Pits, your only escape lies upward. Battle through procedurally shifting infernal layers, bargain with imprisoned demigods for boons, and unravel why you were cast into eternal fire.",
                            DeveloperId = new Guid("7596ad8e-5eaa-44da-a716-6ab508873b52"),
                            Genre = 15,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Pyreclimb+Ascendancy",
                            IsDeleted = false,
                            PublisherId = new Guid("0039fd7b-fdc2-4218-b942-e24ec3f3cf1f"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2020, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pyreclimb Ascendancy"
                        },
                        new
                        {
                            Id = new Guid("ecbda2ec-594d-419d-8b55-9ecb4358ef41"),
                            Description = "Join Zephyr and the Tempest Vanguard in overthrowing the Ironhaven Directorate. Wield crystallized aether in spectacular combat, forge bonds with unlikely allies, and witness a revolution that will reshape the world.",
                            DeveloperId = new Guid("c81c009f-66c6-4c32-9c14-f3c9b68e20a3"),
                            Genre = 16,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Aethershard+Chronicles",
                            IsDeleted = false,
                            PublisherId = new Guid("1a94a706-493a-4ec2-b3e1-3cd802128f59"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2020, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Aethershard Chronicles"
                        },
                        new
                        {
                            Id = new Guid("ab827d8a-311d-46cd-ad74-3742e07bfc5e"),
                            Description = "Command the starship Perihelion through uncharted galaxies. Establish colonies, negotiate with alien civilizations, and uncover the mystery of the Void Echoes—signals from a universe that should not exist.",
                            DeveloperId = new Guid("0dd6b5e3-9d72-4a1a-89b0-a8651c6bebf4"),
                            Genre = 2,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Voidstrider+Odyssey",
                            IsDeleted = false,
                            PublisherId = new Guid("bad774ec-fc82-479d-800c-97c5bd602884"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2023, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Voidstrider Odyssey"
                        },
                        new
                        {
                            Id = new Guid("ed221215-c642-4077-b111-b770619b49c2"),
                            Description = "Awaken in the Tesseract Facility with no memory and a device that folds space. Navigate impossible geometries, outsmart a sardonic AI overseer, and piece together the catastrophe that erased your identity.",
                            DeveloperId = new Guid("07dbe539-557e-4692-85e6-c875b1262a71"),
                            Genre = 11,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Paradox+Chamber",
                            IsDeleted = false,
                            PublisherId = new Guid("e89f7368-94f7-4f55-8e0d-a03333659abb"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2011, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Paradox Chamber"
                        },
                        new
                        {
                            Id = new Guid("31af3372-60e4-4fa2-a2a6-35032f396601"),
                            Description = "When the Takeda clan falls, one warrior survives. Traverse war-scorched Yamashiro Province, master both blade and shadow, and decide whether vengeance or honor will define your path through feudal turmoil.",
                            DeveloperId = new Guid("ae06f7d4-7f50-411d-86af-c97ac324972e"),
                            Genre = 0,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Whisper+of+Daimyo",
                            IsDeleted = false,
                            PublisherId = new Guid("3c77575e-bad2-4408-901b-9ec193a7cfba"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2020, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Whisper of the Daimyo"
                        },
                        new
                        {
                            Id = new Guid("faaa0756-7312-400c-9ba5-a581e4c90faf"),
                            Description = "The wild frontier teems with titanic beasts. Track legendary creatures across volcanic peaks and frozen tundras, craft gear from their remains, and join hunting parties to bring down monsters of mythic proportions.",
                            DeveloperId = new Guid("0b4120ce-a6f9-4b1d-b8d8-de31e4173f7e"),
                            Genre = 8,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Colossus+Hunt+Untamed",
                            IsDeleted = false,
                            PublisherId = new Guid("e23228f4-77a4-448c-b816-ccb1826eed36"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2018, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Colossus Hunt: Untamed"
                        },
                        new
                        {
                            Id = new Guid("bb09f7dd-442f-4e5e-b12c-e13a68fffa2f"),
                            Description = "The realm fractures as noble houses wage shadow wars. Assemble your Veilguard from rogues, mages, and exiled knights, navigate deadly court intrigue, and determine which faction claims the shattered crown.",
                            DeveloperId = new Guid("52753bfd-d052-4ac1-a648-c9ae2fda3ae4"),
                            Genre = 20,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Veilguard+Accord",
                            IsDeleted = false,
                            PublisherId = new Guid("e2b91da3-3f00-4eb4-9785-643acbcf4c55"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2023, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Veilguard Accord"
                        },
                        new
                        {
                            Id = new Guid("2ab1107e-a9a0-4bfc-b366-034ebb4a73a1"),
                            Description = "The World Martial Arts Summit returns with 32 fighters from across the globe. Master unique fighting disciplines, uncover each warrior's personal vendetta, and claim the legendary Iron Championship.",
                            DeveloperId = new Guid("0b4120ce-a6f9-4b1d-b8d8-de31e4173f7e"),
                            Genre = 5,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Iron+Fist+Legends+VI",
                            IsDeleted = false,
                            PublisherId = new Guid("e23228f4-77a4-448c-b816-ccb1826eed36"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2023, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Iron Legends VI"
                        },
                        new
                        {
                            Id = new Guid("38c117e0-2416-4d69-a39a-2b4141c218b2"),
                            Description = "Sail between floating archipelagos in a world torn asunder by magical cataclysm. Recruit a crew of outcasts, uncover the secrets of the Sundering, and restore balance before the remaining islands fall into the void.",
                            DeveloperId = new Guid("7010a2f8-1545-48d8-bb52-86ea0995c45e"),
                            Genre = 8,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Wanderers+Shattered+Isles",
                            IsDeleted = false,
                            PublisherId = new Guid("556474fc-388b-48a7-9bd2-c45528b09bb1"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Wanderers of the Shattered Isles"
                        },
                        new
                        {
                            Id = new Guid("24c4a7ef-7552-4931-ba8b-c5dbe536b323"),
                            Description = "The Hegemony's elite answer humanity's darkest hour. Lead Sergeant Kira Vance through xeno-infested worlds, command squad tactics in brutal firefights, and uncover a conspiracy that threatens the entire frontier.",
                            DeveloperId = new Guid("166ff532-b1c1-40ad-b6ef-85a73d049d1e"),
                            Genre = 7,
                            ImageUrl = "https://via.placeholder.com/300x400?text=Stellarborne+Legionnaires+II",
                            IsDeleted = false,
                            PublisherId = new Guid("ed820b54-96c2-4fbf-a533-09b193c08028"),
                            Rating = 0.0m,
                            ReleaseDate = new DateTime(2024, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Galactic Crusaders II"
                        });
                });

            modelBuilder.Entity("GamingZoneApp.Data.Models.Publisher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identifier for the publisher.");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("Brief information about the publisher.");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("URL of the publisher logo image.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("Name of the publisher.");

                    b.HasKey("Id");

                    b.ToTable("Publishers", t =>
                        {
                            t.HasComment("Publishers in the system.");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0529584-8eb3-4880-8674-c4e5cc67b487"),
                            Description = "International video game publisher recognized for creating atmospheric and psychologically intense horror games that push the boundaries of interactive storytelling.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Phantom+Gate",
                            Name = "Phantom Gate Publishing"
                        },
                        new
                        {
                            Id = new Guid("f128d30f-d5df-4ea2-9638-6a3f2aef82dd"),
                            Description = "European video game publisher and distributor known for supporting independent studios and publishing award-winning narrative-driven games.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Crimson+Forge+Pub",
                            Name = "Crimson Forge Publishing"
                        },
                        new
                        {
                            Id = new Guid("8baa78a8-4139-409e-b8ab-78aac5b5fc48"),
                            Description = "Major video game publisher specializing in action-packed games and collaborations with renowned developers to create premium gaming experiences.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Dragon+Crown",
                            Name = "Dragon Crown Entertainment"
                        },
                        new
                        {
                            Id = new Guid("e23228f4-77a4-448c-b816-ccb1826eed36"),
                            Description = "Established video game publisher known for creating legendary survival horror franchises and action games with exceptional design and storytelling.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Phoenix+Rising+Pub",
                            Name = "Phoenix Rising Publishing"
                        },
                        new
                        {
                            Id = new Guid("3c77575e-bad2-4408-901b-9ec193a7cfba"),
                            Description = "Major video game publisher famous for publishing exclusive titles and supporting innovative game development across multiple platforms.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Nexus+Global",
                            Name = "Nexus Global Entertainment"
                        },
                        new
                        {
                            Id = new Guid("b037a40e-b701-4bdc-a5c0-96b0fdd92619"),
                            Description = "Independent publisher known for releasing meticulously crafted indie games with exceptional artistic vision and challenging gameplay.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Pixel+Hollow+Pub",
                            Name = "Pixel Hollow Publishing"
                        },
                        new
                        {
                            Id = new Guid("0039fd7b-fdc2-4218-b942-e24ec3f3cf1f"),
                            Description = "Independent video game publisher renowned for creating visually stunning games with exceptional soundtracks and innovative gameplay mechanics.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Ember+Flame+Pub",
                            Name = "Ember Flame Publishing"
                        },
                        new
                        {
                            Id = new Guid("1a94a706-493a-4ec2-b3e1-3cd802128f59"),
                            Description = "Major video game publisher known for publishing epic JRPGs and iconic franchises with memorable characters and engaging storytelling.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Crystal+Dawn+Pub",
                            Name = "Crystal Dawn Publishing"
                        },
                        new
                        {
                            Id = new Guid("bad774ec-fc82-479d-800c-97c5bd602884"),
                            Description = "Leading video game publisher famous for publishing massive open-world RPGs and supporting innovative game development.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Starbound+Pub",
                            Name = "Starbound Publishing"
                        },
                        new
                        {
                            Id = new Guid("e89f7368-94f7-4f55-8e0d-a03333659abb"),
                            Description = "Innovative video game publisher and digital distribution platform known for genre-defining games and digital distribution excellence.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Quantum+Rift+Pub",
                            Name = "Quantum Rift Publishing"
                        },
                        new
                        {
                            Id = new Guid("e2b91da3-3f00-4eb4-9785-643acbcf4c55"),
                            Description = "European video game publisher known for publishing deep, story-rich RPGs with complex mechanics, multiple endings, and exceptional player agency.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Arcane+Depths+Pub",
                            Name = "Arcane Depths Publishing"
                        },
                        new
                        {
                            Id = new Guid("556474fc-388b-48a7-9bd2-c45528b09bb1"),
                            Description = "Independent video game publisher known for supporting innovative action RPGs and artistic games from talented developers with unique creative vision.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Prism+Voyage+Pub",
                            Name = "Prism Voyage Publishing"
                        },
                        new
                        {
                            Id = new Guid("ed820b54-96c2-4fbf-a533-09b193c08028"),
                            Description = "International video game publisher known for publishing action-packed games and supporting diverse game genres from independent to AAA studios.",
                            ImageUrl = "https://via.placeholder.com/300x300?text=Titan+Forge+Pub",
                            Name = "Titan Forge Publishing"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GamingZoneApp.Data.Models.ApplicationUserGame", b =>
                {
                    b.HasOne("GamingZoneApp.Data.Models.Game", "Game")
                        .WithMany("GamesUsers")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamingZoneApp.Data.Models.ApplicationUser", "User")
                        .WithMany("UsersGames")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GamingZoneApp.Data.Models.Game", b =>
                {
                    b.HasOne("GamingZoneApp.Data.Models.Developer", "Developer")
                        .WithMany("GamesDeveloped")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamingZoneApp.Data.Models.Publisher", "Publisher")
                        .WithMany("GamesPublished")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamingZoneApp.Data.Models.ApplicationUser", "User")
                        .WithMany("CreatedGames")
                        .HasForeignKey("UserId");

                    b.Navigation("Developer");

                    b.Navigation("Publisher");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("GamingZoneApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("GamingZoneApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamingZoneApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("GamingZoneApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamingZoneApp.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("CreatedGames");

                    b.Navigation("UsersGames");
                });

            modelBuilder.Entity("GamingZoneApp.Data.Models.Developer", b =>
                {
                    b.Navigation("GamesDeveloped");
                });

            modelBuilder.Entity("GamingZoneApp.Data.Models.Game", b =>
                {
                    b.Navigation("GamesUsers");
                });

            modelBuilder.Entity("GamingZoneApp.Data.Models.Publisher", b =>
                {
                    b.Navigation("GamesPublished");
                });
#pragma warning restore 612, 618
        }
    }
}
